#ifndef SERVICESTATUSDIALOG_H
#define SERVICESTATUSDIALOG_H

#include <QDialog>
#include <QTableWidget>
#include <QLabel>
#include <QTimer>
#include "DockerManager.h"
#include "ConfigManager.h"

// Forward declaration of the UI class generated by uic
namespace Ui {
    class ServiceStatusDialog;
}

class ServiceStatusDialog : public QDialog {
    Q_OBJECT

public:
    explicit ServiceStatusDialog(ConfigManager* configManager, DockerManager* dockerManager, QWidget *parent = nullptr);
    ~ServiceStatusDialog();

private slots:
    void updateStatus();
    void updateDockerInfo();
    void refreshAllData();

private:
    void setupConnections();
    void populateServiceStatus();
    void populateDockerContainers();
    void applyStyling(); // For any styling not covered by .ui or to override
    void updateDockerStatCards(int running, int total, int images);

    Ui::ServiceStatusDialog *ui; // Pointer to the UI components
    ConfigManager* appConfigManager;
    DockerManager* appDockerManager;
    QTimer *timer;
};

#endif // SERVICESTATUSDIALOG_H